<?php

namespace AppBundle\Repository;

/**
 * BirdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirdsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllByBirdRaceAsc() 
	{
		return $this
			->createQueryBuilder('b') // On construit la query qui recupère toutes les races via le querybuilder
			->orderBy('b.race', 'ASC') // On les tri par race alphabetique
			->getQuery() // On crée la query
			->getResult(); // On retourne le résultat
	} // End findAllByBirdRaceAsc()
}
