# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # Encryption on user data
    encoders:
        AppBundle\Entity\Users: bcrypt
        FOS\UserBundle\Model\UserInterface: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    role_hierarchy:
        ROLE_PARTICULIER: ROLE_USER
        ROLE_NATURALISTE: [ROLE_PARTICULIER, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN: [ROLE_NATURALISTE, ROLE_PARTICULIER, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_NATURALISTE, ROLE_PARTICULIER, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: fos_userbundle
            logout:
                path: /deconnexion
            access_denied_url: /access_refuse
            form_login:
                login_path: /connexion
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
                default_target_path: /profil
            remember_me:
                secret: '%secret%'

    access_control:
        - { path: /profil, roles: ROLE_PARTICULIER }
        - { path: /ajouter_observation, roles: ROLE_PARTICULIER }
        - { path: ^/modifier_observation, roles: ROLE_PARTICULIER }
        - { path: ^/signaler_observation, roles: ROLE_PARTICULIER }
        - { path: /liste_observation, roles: ROLE_NATURALISTE }
        - { path: ^/publier_observation, roles: ROLE_NATURALISTE }
        - { path: /liste_utilisateur, roles: ROLE_ADMIN }
        - { path: ^/naturaliser_utilisateur, roles: ROLE_ADMIN }
        - { path: ^/retrograder_utilisateur, roles: ROLE_ADMIN }
        - { path: ^/supprimer_utilisateur, roles: ROLE_ADMIN }
        - { path: ^/suppression_observation, roles: ROLE_ADMIN }
        - { path: /tableau_de_bord, roles: ROLE_ADMIN }
        - { path: /add_news, roles: ROLE_ADMIN }
        - { path: /remove_news, roles: ROLE_ADMIN }
