<?php

namespace BlogBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllByDateAsc() 
	{
		return $this
			->createQueryBuilder('n') // On construit la query qui recupère toutes les news via le querybuilder
			->orderBy('n.datePublished', 'DESC') // On les tri par date croissant
			->getQuery() // On crée la query
			->getResult(); // On retourne le résultat
	} // End findAllByDateAsc()
}
